# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'record.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(422, 335)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.PeriodCheck = QtWidgets.QComboBox(Dialog)
        self.PeriodCheck.setObjectName("PeriodCheck")
        self.gridLayout.addWidget(self.PeriodCheck, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 9, 0, 1, 3)
        self.WorkEdit = QtWidgets.QTextEdit(Dialog)
        self.WorkEdit.setObjectName("WorkEdit")
        self.gridLayout.addWidget(self.WorkEdit, 6, 2, 1, 1)
        self.WorkCheck = QtWidgets.QComboBox(Dialog)
        self.WorkCheck.setObjectName("WorkCheck")
        self.gridLayout.addWidget(self.WorkCheck, 0, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.year = QtWidgets.QComboBox(Dialog)
        self.year.setObjectName("year")
        self.gridLayout_2.addWidget(self.year, 1, 0, 1, 1)
        self.mounth = QtWidgets.QComboBox(Dialog)
        self.mounth.setObjectName("mounth")
        self.gridLayout_2.addWidget(self.mounth, 1, 1, 1, 1)
        self.date = QtWidgets.QComboBox(Dialog)
        self.date.setObjectName("date")
        self.gridLayout_2.addWidget(self.date, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.movable = QtWidgets.QCheckBox(Dialog)
        self.movable.setObjectName("movable")
        self.gridLayout.addWidget(self.movable, 7, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.endhour = QtWidgets.QSpinBox(Dialog)
        self.endhour.setWrapping(True)
        self.endhour.setAccelerated(False)
        self.endhour.setMaximum(23)
        self.endhour.setProperty("value", 7)
        self.endhour.setObjectName("endhour")
        self.gridLayout_3.addWidget(self.endhour, 1, 3, 1, 1)
        self.startminute = QtWidgets.QSpinBox(Dialog)
        self.startminute.setWrapping(True)
        self.startminute.setAccelerated(False)
        self.startminute.setMaximum(59)
        self.startminute.setSingleStep(5)
        self.startminute.setObjectName("startminute")
        self.gridLayout_3.addWidget(self.startminute, 1, 1, 1, 1)
        self.starthour = QtWidgets.QSpinBox(Dialog)
        self.starthour.setWrapping(True)
        self.starthour.setAccelerated(False)
        self.starthour.setMaximum(23)
        self.starthour.setProperty("value", 7)
        self.starthour.setObjectName("starthour")
        self.gridLayout_3.addWidget(self.starthour, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 2, 1, 1)
        self.endminute = QtWidgets.QSpinBox(Dialog)
        self.endminute.setWrapping(True)
        self.endminute.setAccelerated(False)
        self.endminute.setMaximum(59)
        self.endminute.setSingleStep(5)
        self.endminute.setProperty("value", 30)
        self.endminute.setObjectName("endminute")
        self.gridLayout_3.addWidget(self.endminute, 1, 4, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 4, 2, 1, 1)
        self.Concentrate = QtWidgets.QCheckBox(Dialog)
        self.Concentrate.setObjectName("Concentrate")
        self.gridLayout.addWidget(self.Concentrate, 8, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.PeriodCheck.setCurrentIndex(-1)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Новая запись"))
        Dialog.setWindowIcon(QtGui.QIcon('icon.png'))
        self.label_9.setText(_translate("Dialog", "Время"))
        self.label.setText(_translate("Dialog", "Тип работы"))
        self.label_5.setText(_translate("Dialog", "Месяц"))
        self.label_6.setText(_translate("Dialog", "Число"))
        self.label_4.setText(_translate("Dialog", "Год"))
        self.label_2.setText(_translate("Dialog", "Период повторения"))
        self.movable.setText(_translate("Dialog", "Невозможно сместить в расписании"))
        self.label_3.setText(_translate("Dialog", "Короткое название"))
        self.label_7.setText(_translate("Dialog", "Дата"))
        self.label_8.setText(_translate("Dialog", "-"))
        self.Concentrate.setText(_translate("Dialog", "Требуется концентрация на работе"))
